### ISSUE TITLE
newrelic/newrelic:3.23.0 version are not yet supported by terrap

### ISSUE THREAD

**Issue by thiago-scherrer** [sirrend/terrap-cli#8]
Hello! 

I tried to use Terrap to validate my Terraform code, where I use it to manage New Relic dashboards, alerts, and other resources. However, I encountered the following error:

```sh

$ terrap init                        
🚀 Initializing directory...
🖥️  Using Terraform version: 1.1.7
🧰 Looking for providers... Done!
👋 Saving workspace... Done!

$ terrap scan                        
The following providers and corresponding versions are not yet supported by terrap: newrelic/newrelic:3.23.0 😢
Check again soon! We're actively working on increasing our Providers support 🏗️
```

Is there any supported version or roadmap for implementation?
Congratulations on the project!

**Comment by yuvalpress** [comment]
Hi @thiago-scherrer! thank you for your patience.
All of the NewRelic Terraform provider versions are now supported :)
